#ifndef SLA_SUPPORTPOINT_HPP
#define SLA_SUPPORTPOINT_HPP

#include <algorithm>
#include <atomic>
#include <cstddef>

#include <libslic3r/Point.hpp>

namespace Slic3r { namespace sla {

// An enum to keep track of where the current points on the ModelObject came from.
enum class PointsStatus {
    NoPoints,           // No points were generated so far.
    Generating,     // The autogeneration algorithm triggered, but not yet finished.
    AutoGenerated,  // Points were autogenerated (i.e. copied from the backend).
    UserModified    // User has done some edits.
};

// Ported from PrusaSlicer 2.9.1: three-value classification replacing bool is_new_island.
// File format encoding (float, range-based, compatible with PrusaSlicer 2.9.1+):
//   ≈1.0 (0.999–1.001) → island      (same as old is_new_island=true)
//   ≈2.0 (1.999–2.001) → manual_add  (new)
//   ≈3.0 (2.999–3.001) → slope       (new)
//   all other values   → slope        (legacy fallback: old is_new_island=false → slope)
enum class SupportPointType {
    manual_add = 0, // User manually placed, or promoted by dragging an auto-generated point
    island     = 1, // Auto-generated on a completely new island (prev_parts.empty())
    slope      = 2, // Auto-generated on an overhang / peninsula
};

// Per-point weight classification for manually-placed support points.
// Kept for UI display (L/M/H button highlight) only; geometry uses pillar_radius directly.
enum class SupportWeight {
    Light  = 0,
    Medium = 1,
    Heavy  = 2,
};

// Sentinel: fields < 0 mean "use global SLA print preset" (auto-generated points).
// Manual points store explicit values at placement time (mode 2 workflow).
static constexpr float SUPPORT_POINT_USE_PRESET = -1.f;

struct SupportPoint
{
    Vec3f            pos;
    float            head_front_radius;
    SupportPointType type;
    SupportWeight    weight = SupportWeight::Medium;
    float            pillar_radius = 0.f; // 0 = use global config (auto points); >0 = per-point override (manual points)
    float            base_radius_mm        = SUPPORT_POINT_USE_PRESET; // Support Bottom Diameter / 2
    float            support_bracing_angle_deg = SUPPORT_POINT_USE_PRESET; // Support Bracing Angle (degrees)
    float            head_penetration_mm    = SUPPORT_POINT_USE_PRESET; // Contact depth
    float            head_width_mm          = SUPPORT_POINT_USE_PRESET; // Head connection length
    float            head_back_radius_mm    = SUPPORT_POINT_USE_PRESET; // Lower diameter / 2
    float            contact_sphere_radius  = SUPPORT_POINT_USE_PRESET; // 0 = no sphere; >0 = sphere radius; <0 = use preset

    SupportPoint()
        : pos(Vec3f::Zero()), head_front_radius(0.f), type(SupportPointType::manual_add)
    {}

    SupportPoint(float pos_x,
                 float pos_y,
                 float pos_z,
                 float head_radius,
                 SupportPointType t = SupportPointType::manual_add)
        : pos(pos_x, pos_y, pos_z)
        , head_front_radius(head_radius)
        , type(t)
    {}

    SupportPoint(Vec3f position, float head_radius, SupportPointType t = SupportPointType::manual_add)
        : pos(position)
        , head_front_radius(head_radius)
        , type(t)
    {}

    // Construct from serialized 5-float vector (legacy & new format).
    // Encoding matches PrusaSlicer 2.9.1 range-based scheme.
    SupportPoint(Eigen::Matrix<float, 5, 1, Eigen::DontAlign> data)
        : pos(data(0), data(1), data(2))
        , head_front_radius(data(3))
    {
        float v = data(4);
        if (v > 0.999f && v < 1.001f)
            type = SupportPointType::island;
        else if (v > 1.999f && v < 2.001f)
            type = SupportPointType::manual_add;
        else if (v > 2.999f && v < 3.001f)
            type = SupportPointType::slope;
        else
            type = SupportPointType::slope; // legacy is_new_island=false → slope
        // pillar_radius defaults to 0.f; set from 6th float by 3mf.cpp (version 2)
    }

    bool is_island() const { return type == SupportPointType::island; }

    bool operator==(const SupportPoint &sp) const
    {
        float rdiff = std::abs(head_front_radius - sp.head_front_radius);
        float prdiff = std::abs(pillar_radius - sp.pillar_radius);
        return (pos == sp.pos) && rdiff < float(EPSILON) &&
               type == sp.type && weight == sp.weight && prdiff < float(EPSILON) &&
               std::abs(base_radius_mm - sp.base_radius_mm) < float(EPSILON) &&
               std::abs(support_bracing_angle_deg - sp.support_bracing_angle_deg) < float(EPSILON) &&
               std::abs(head_penetration_mm - sp.head_penetration_mm) < float(EPSILON) &&
               std::abs(head_width_mm - sp.head_width_mm) < float(EPSILON) &&
               std::abs(head_back_radius_mm - sp.head_back_radius_mm) < float(EPSILON) &&
               std::abs(contact_sphere_radius - sp.contact_sphere_radius) < float(EPSILON);
    }

    bool operator!=(const SupportPoint &sp) const { return !(sp == (*this)); }

    bool has_explicit_geometry() const
    {
        return type == SupportPointType::manual_add &&
               (head_penetration_mm >= 0.f || head_width_mm >= 0.f ||
                contact_sphere_radius >= 0.f || pillar_radius > 0.f || base_radius_mm >= 0.f);
    }

    template<class Archive> void serialize(Archive &ar)
    {
        ar(pos, head_front_radius, type, weight, pillar_radius, base_radius_mm, support_bracing_angle_deg,
           head_penetration_mm, head_width_mm, head_back_radius_mm, contact_sphere_radius);
    }
};

// Contact depth on the point / preset: distance from the model contact point (sp.pos) along
// -normal into the model (sphere touch point when sphere mode, pin contact when none).
inline float point_contact_front_depth_mm(const SupportPoint &sp, double preset_mm)
{
    return sp.head_penetration_mm >= 0.f ? sp.head_penetration_mm : float(preset_mm);
}

inline float point_head_penetration_mm(const SupportPoint &sp, double preset_mm)
{
    return point_contact_front_depth_mm(sp, preset_mm);
}

// Head::penetration_mm for meshing: maps front depth to pinhead coordinates when a contact sphere is used.
inline float point_head_penetration_mesh_mm(const SupportPoint &sp, double preset_mm,
                                            double pin_r_mm, double contact_r_mm)
{
    const float front = point_contact_front_depth_mm(sp, preset_mm);
    if (contact_r_mm <= EPSILON)
        return front;
    return front + float(pin_r_mm) - float(contact_r_mm);
}

// --- fix-sla-thin-model-support-points (#5): dynamic anti-penetration clamp ---
//
// Two pure functions, shared verbatim by the slicer (SupportTreeBuildsteps,
// BranchingTreeSLA) and by the GUI preview, so the two ends can never disagree
// about how deep a head is allowed to go. No mesh, no config, no state: the
// caller measures the local thickness and passes it in.
//
// NOTE: these do NOT touch point_head_penetration_mesh_mm() above. Its mapping
// from front depth to mesh-space Head::penetration_mm is unchanged; the clamp
// runs on the front depth *before* that conversion.

// Distance between a head's front depth and the deepest point of the pinhead
// geometry that will actually be emitted. This is the spec's `offset` term.
//
// Derived from pinhead() (SupportTreeMesher.cpp) and head_mesh_body()
// (SupportTreeMesher.hpp): after head_mesh_body()'s z-shift the pin ball's top
// sits exactly at Head::penetration_mm, and the contact sphere's top sits at
// penetration_mm - r_pin + r_contact. Substituting the mesh-space mapping
// penetration_mm = front + r_pin - r_contact puts the contact sphere top
// exactly on `front`.
//
//   no contact sphere (r_contact <= EPSILON)
//       penetration_mm == front, deepest geometry is the pin ball top == front
//   contact sphere live (r_contact > r_pin)
//       deepest geometry is the contact sphere top == front
//   degenerate band (0 < r_contact <= r_pin)
//       head_mesh_body() appends a contact sphere only when r_contact > r_pin,
//       so no sphere is emitted -- yet point_head_penetration_mesh_mm()
//       converts regardless. The pin ball top, and therefore the deepest point,
//       lands at front + (r_pin - r_contact).
//
// That degenerate band is a PRE-EXISTING inconsistency between
// point_head_penetration_mesh_mm() and head_mesh_body(). This change
// deliberately does not fix it -- this offset term exists so the clamp stays
// correct in spite of it.
inline double head_deepest_point_offset(double pin_r_mm, double contact_r_mm)
{
    return (contact_r_mm > EPSILON && contact_r_mm <= pin_r_mm)
               ? pin_r_mm - contact_r_mm
               : 0.;
}

// Clamp a head's front depth so the emitted geometry stays inside the material.
//
//   front_clamped = clamp(min(configured_front, local_thickness/2 - offset),
//                         0, configured_front)
//
// Half the local thickness is the target: the head stops at the mid-plane
// rather than at the far surface, which is what keeps the tip clear of the
// load-bearing face's other side under the "no bumps on the top surface"
// policy. local_thickness is measured along the head axis by the caller (see
// measure_available_depth() in SupportTreeUtils.hpp).
//
// A non-positive configured depth is returned untouched: it cannot penetrate
// anything, so there is nothing to clamp, and passing it through also keeps
// std::clamp's lo <= hi precondition intact (clamping into [0, negative] is
// undefined behaviour).
//
// A negative or zero local_thickness -- a mesh so thin the offset alone
// overruns it, as in the degenerate band -- naturally falls out as 0, i.e. the
// head just touches the surface without entering. That is the intended
// fail-safe direction.
inline double clamp_front_depth(double configured_front_mm,
                                double local_thickness_mm,
                                double pin_r_mm,
                                double contact_r_mm)
{
    if (configured_front_mm <= 0.)
        return configured_front_mm;

    const double usable = local_thickness_mm * 0.5 -
                          head_deepest_point_offset(pin_r_mm, contact_r_mm);

    return std::clamp(std::min(configured_front_mm, usable), 0., configured_front_mm);
}

// Front depth <-> Head::penetration_mm, the two directions of the mapping that
// point_head_penetration_mesh_mm() applies. Split out because the clamp runs on
// the front depth while the commit points hold a mesh-space penetration; both
// directions are needed and they must stay exact inverses of each other.
inline double front_depth_to_mesh_penetration(double front_mm,
                                              double pin_r_mm,
                                              double contact_r_mm)
{
    return contact_r_mm <= EPSILON ? front_mm
                                   : front_mm + pin_r_mm - contact_r_mm;
}

inline double mesh_penetration_to_front_depth(double penetration_mm,
                                              double pin_r_mm,
                                              double contact_r_mm)
{
    return contact_r_mm <= EPSILON ? penetration_mm
                                   : penetration_mm - pin_r_mm + contact_r_mm;
}

// Counts how many support heads could not have their available depth measured
// during one support tree generation.
//
// On a closed manifold mesh the probe ray always hits, so a miss means the mesh
// is broken. Those heads fall back to zero penetration (the "no bumps on the
// top surface" policy) and the driver reports the total in a single summary log
// line -- never one line per point, which on a badly broken mesh would be tens
// of thousands of lines.
//
// Atomic because the Branching tree runs pinhead placement under ex_tbb.
struct DepthProbeMissCounter
{
    std::atomic<size_t> misses{0};

    void   note()        { misses.fetch_add(1, std::memory_order_relaxed); }
    size_t count() const { return misses.load(std::memory_order_relaxed); }
};

inline float point_head_width_mm(const SupportPoint &sp, double preset_mm)
{
    return sp.head_width_mm >= 0.f ? sp.head_width_mm : float(preset_mm);
}

inline float point_contact_sphere_radius_mm(const SupportPoint &sp, double preset_mm)
{
    return sp.contact_sphere_radius >= 0.f ? sp.contact_sphere_radius : float(preset_mm);
}

inline float point_head_back_radius_mm(const SupportPoint &sp, double preset_mm)
{
    return sp.head_back_radius_mm >= 0.f ? sp.head_back_radius_mm : float(preset_mm);
}

inline bool point_uses_contact_sphere(const SupportPoint &sp, bool preset_sphere)
{
    return sp.contact_sphere_radius >= 0.f ? sp.contact_sphere_radius > float(EPSILON) : preset_sphere;
}

using SupportPoints = std::vector<SupportPoint>;

}} // namespace Slic3r::sla

#endif // SUPPORTPOINT_HPP
