name: Mac Weekly

on:
  schedule:
    # Friday 22:00 UTC+8 -> Friday 14:00 UTC
    - cron: '0 14 * * 5'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check_changes:
    name: Check branch changes in last 7 days
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Checkout repo (default branch)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Determine if phrozen-custom-dev had commits in last week
        id: check
        shell: bash
        run: |
          set -euo pipefail
          git fetch origin phrozen-custom-dev:phrozen-custom-dev
          last_ts=$(git log -1 --format=%ct phrozen-custom-dev)
          now=$(date +%s)
          week=$((7*24*60*60))
          if [ $((now - last_ts)) -le $week ]; then
            echo "should_build=true" >> "$GITHUB_OUTPUT"
            echo "New commits detected on phrozen-custom-dev within 7 days."
          else
            echo "should_build=false" >> "$GITHUB_OUTPUT"
            echo "No new commits on phrozen-custom-dev in last 7 days. Skipping build."
          fi

  build_mac:
    name: Build macOS unsigned DMG
    needs: [check_changes]
    if: needs.check_changes.outputs.should_build == 'true'
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: macos-14
      arch: arm64
      build-deps-only: false
      sign-and-notarize: false
    secrets: inherit
