name: Windows Nightly

on:
  schedule:
    # 22:00 UTC+8 daily -> 14:00 UTC
    - cron: '0 14 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  check_changes:
    name: Check branch changes in last 24h
    runs-on: ubuntu-latest
    outputs:
      should_build: ${{ steps.check.outputs.should_build }}
    steps:
      - name: Checkout repo (default branch)
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Determine if phrozen-custom-dev has new commits
        id: check
        shell: bash
        run: |
          set -euo pipefail
          git fetch origin phrozen-custom-dev:phrozen-custom-dev
          last_ts=$(git log -1 --format=%ct phrozen-custom-dev)
          now=$(date +%s)
          day=$((24*60*60))
          if [ $((now - last_ts)) -le $day ]; then
            echo "should_build=true" >> "$GITHUB_OUTPUT"
            echo "New commits detected on phrozen-custom-dev within 24h."
          else
            echo "should_build=false" >> "$GITHUB_OUTPUT"
            echo "No new commits on phrozen-custom-dev in last 24h. Skipping build."
          fi

  build_windows:
    name: Build Windows portable + PDB
    needs: [check_changes]
    if: needs.check_changes.outputs.should_build == 'true'
    uses: ./.github/workflows/build_check_cache.yml
    with:
      os: windows-latest
      build-deps-only: false
      build-installer: false
    secrets: inherit
